In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [3]:
y.shape, tX.shape

((250000,), (250000, 30))

## Do your thing crazy machine learning thing here :) ...

In [4]:
import datetime
from implementations import *


[0 1 2 3 4 5]


Gradient Descent test:

In [5]:
"""taken from ex02:"""
# from gradient_descent import *

# Define the parameters of the algorithm.
max_iters = 1000
gamma = 1e-9

# Initialization
w_initial = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
#A=tX[0:30]
#b=y[0:30]
#w_initial=np.linalg.lstsq(A,b,rcond=None)[0]
print(np.shape(tX))

b=variance_half_max_index(tX)
tX1=tX[:,b]
print(np.shape(tX1))

# Start gradient descent.
start_time = datetime.datetime.now()
gradient_w, gradient_loss = least_square(y, tX1)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("Gradient Descent: execution time={t:.3f} seconds".format(t=exection_time))
print("gradient loss = ", gradient_loss, "\n W = ",gradient_w)

(250000, 30)
(250000, 24)
Gradient Descent: execution time=0.079 seconds
gradient loss =  0.3559770984135593 
 W =  [ 2.26971848e-04  6.56522489e-04 -2.07872311e-03  2.66859544e+00
  3.25911884e-04  2.67330024e+00  5.00287345e-03 -9.31223839e-03
 -1.75704625e-03 -2.00046630e-03  2.66082659e+00 -2.66378165e+00
 -6.79222194e-04  2.79992082e-04 -3.52941170e-02 -6.10160688e-03
 -1.00960843e-02  1.08584292e-01 -5.86224270e-02  1.14536818e-03
 -4.51466862e-04 -1.26157626e-03  1.86677641e-03  5.58306206e-04]


Least squares (using normal equations) test:

In [6]:
# Start.
start_time = datetime.datetime.now()
weights, loss = least_squares(y, tX)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("Least squares: execution time={t:.3f} seconds".format(t=exection_time))
print("Loss = ", loss, "\n W = ", weights)

Least squares: execution time=0.780 seconds
Loss =  0.3396868094770345 
 W =  [ 8.03494350e-05 -7.20202266e-03 -6.05417273e-03 -5.47559077e-04
 -1.93874687e-02  4.73451613e-04 -2.60379057e-02  3.25106299e-01
 -3.80780015e-05 -2.72785402e+00 -2.21220141e-01  9.50794097e-02
  6.40351607e-02  2.73611370e+00 -3.31801097e-04 -9.54325136e-04
  2.74087044e+00 -5.34165258e-04  9.73498900e-04  3.69225050e-03
  3.54487183e-04 -5.43344617e-04 -3.30448035e-01 -1.40800497e-03
  8.31432840e-04  1.02117276e-03 -1.68047418e-03 -5.83664795e-03
 -1.11088002e-02  2.72831395e+00]


Ridge regression (using normal equations) test:

In [14]:
lambda_ = 0.5

# Start.
start_time = datetime.datetime.now()
weights, loss = ridge_regression(y, tX, lambda_)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("Least squares: execution time={t:.3f} seconds".format(t=exection_time))
print("Loss = ", loss, "\n W = ", weights)

[0 1 2 3 4 5]
Least squares: execution time=0.746 seconds
Loss =  0.3516066841491274 
 W =  [ 2.48519324e-04 -8.96465390e-03 -2.24753247e-03 -2.19688733e-03
 -8.28785858e-04  5.27482033e-04 -1.23580011e-02  2.78401608e-02
  6.37660259e-05  3.17281194e-03 -2.55552723e-02  4.56064526e-02
  1.07748012e-02  6.17277403e-03 -3.38880835e-04 -1.20732147e-03
  2.51582382e-03 -4.25916162e-04  8.32986709e-04  4.90332267e-03
  4.17025377e-04 -7.70891369e-04 -2.48302577e-02  1.45686817e-03
 -7.63838506e-04 -5.43201301e-04  2.59945303e-04  1.61198112e-03
  1.83180262e-04 -5.51499664e-03]


Polynomial:

In [9]:
"""x1 = np.arange(40)
x1 = x1.reshape(10, -1)
print(x1)
x_poly = build_poly(x1, 3)
print(x_poly)"""

'x1 = np.arange(40)\nx1 = x1.reshape(10, -1)\nprint(x1)\nx_poly = build_poly(x1, 3)\nprint(x_poly)'

In [50]:
lambda_ = 0.0
#0.0093 meilleur pour le moment 
# Start.
start_time = datetime.datetime.now()
print(np.shape(tX))
tX_poly=build_poly_variance(tX,1)
#tX_poly = build_poly(tX, 3)
print(np.shape(tX_poly))
weights, loss = ridge_regression(y, tX_poly, lambda_)
end_time = datetime.datetime.now()

# Print result
exection_time = (end_time - start_time).total_seconds()
print("Least squares: execution time={t:.3f} seconds".format(t=exection_time))
print("Loss = ", loss, "\n W = ", weights)

[0 1 2 3 4 5]
(250000, 30)
0
1
2
3
4
5
6
7
8
9
(250000, 87)
Least squares: execution time=4.511 seconds
Loss =  0.3141378690167801 
 W =  [ 2.90364786e-01  1.29267911e-05 -1.62442201e-03  1.64183734e-05
  3.04295343e-01 -3.60121522e-05 -2.11591134e-04  1.42518085e-05
 -1.24749462e-08 -1.41837717e-02  7.17531653e-05 -9.18181729e-08
 -1.44957144e-03 -2.22635535e-06  4.16439883e-09  1.16475138e-04
 -3.63473579e-06  3.27147939e-09  2.91702336e-01 -6.21527618e-06
  3.11823828e-09 -2.93262988e-01  3.51244891e-06 -1.26174832e-09
 -5.00262114e-05  2.15719914e-06 -1.10216259e-08  1.25027237e-11
 -3.89618434e-15  2.19364316e-02 -8.26751015e-05  5.91818440e-08
  8.39813269e-11 -8.13287775e-14 -7.08473540e-02 -2.61188769e-03
  3.73297253e-04 -3.42603528e-07 -2.33494640e-10 -4.57415405e-03
  3.39407825e-02  7.11278632e-04 -3.41473002e-07  4.48944450e-11
 -5.97668239e-03 -7.15063164e-03  8.67878195e-04  1.68924168e-07
 -1.52179343e-10  4.12826862e-01 -1.36930381e-02 -1.27637890e-03
 -2.89456186e-07 

## Generate predictions and save ouput in csv format for submission:

In [10]:
DATA_TEST_PATH = '../data/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [51]:
#tX_test_poly = build_poly(tX_test, 3)
tX_test_poly=build_poly_variance(tX,1)

y_pred = predict_labels(weights, tX_test_poly)
#print(weights)
print("Test: Loss = ", compute_loss(y_pred, tX_test_poly, weights))
#meilleur pour le moment à 0.1754
#0.1845 sans terme indépendant. 

0
1
2
3
4
5
6
7
8
9
Test: Loss =  0.18451719746424602


In [54]:
OUTPUT_PATH = '../data/result.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test_poly)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)